parameters:
    jwt_cookie_secure_default: false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Security\JwtCookieManager:
        arguments:
            $secureCookie: '%env(bool:default:jwt_cookie_secure_default:JWT_COOKIE_SECURE)%'
